modLoader="javafml"
loaderVersion="[47,)"
license="Apache License 2.0"

[[mods]]
modId="travelanchors"
version="${version}"
displayName="Travel Anchors"
displayURL="https://www.curseforge.com/minecraft/mc-mods/travel-anchors-forge"
credits="CastCrafter, MelanX, noeppi_noeppi"
authors="Th-Underscore"
description='''
Adds a staff of travelling and a travel anchor to teleport around the world.
'''

[[dependencies.travelanchors]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,47.4.0]"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelanchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelanchors]]
    modId="libx"
    mandatory=true
    versionRange="[${libx_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelanchors]]
    modId="irons_spellbooks"
    mandatory=false
    versionRange="[${irons_spells_version},)"
    ordering="NONE"
    side="BOTH"
